### ISSUE TITLE
Get Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. 

### ISSUE THREAD

**Issue by mregan59** [IjzerenHein/react-navigation-magic-move#1]
I'm trying to get this snack that uses this with react-native-router-flux to work: https://snack.expo.io/@mern59/react-native-magic-move-copy but I keep getting that error on the initial load. 

![Screen Shot 2019-03-12 at 10 00 54 PM](https://user-images.githubusercontent.com/5798932/54248632-cdbe3280-4513-11e9-9ed2-640c9b6c45c5.png)

I have a project of my own that is using react-native-router-flux that I was trying to use this on that is also experiencing this error: https://snack.expo.io/@mern59/animation:-flowers-new. On mine I don't get the error initially but as soon as I try to navigate it shows. If I remove **import "react-navigation-magic-move"** it works but I would like to use it so I can have animation on the back button.

**Comment by IjzerenHein** [comment]
Hmm, the code for this lib is very slim and not much can go wrong tbh. It uses `NavigationEvents` from `react-navigation` to monitor the navigation state. Is it possible that you are using a `MagicMove.Scene` outside the navigation hierarchy?
