### ISSUE TITLE
Animation only shown when navigating back after adding import statement

### ISSUE THREAD

**Issue by thijs-qv** [IjzerenHein/react-navigation-magic-move#3]
### Actual behaviour
When adding `import "react-navigation-magic-move";` the animation is shown when navigating back to the previous MagicMove.Scene, but the animation when navigating to a new MagicMove.Scene is not shown anymore. Without adding the import statement, the animation is showing correctly when navigating to another MagicMove.Scene, but not when navigating back.

### Expected behaviour
Animation should be shown when navigating to new MagicMove.Scene as well as when going back to the previous MagicMove.Scene.

### I'm seeing this behaviour on
- Device: iOS simulator iOS 11.4.
- Routing/transition library: react-navigation v3.12.1
- React-native version: v0.60.5
- react-native-magic-move version: v0.6.6
- react-navigation-magic-move version: v0.4.1

Really cool library, by the way!

**Comment by IjzerenHein** [comment]
How does your navigation setup look like Are you using a stack-navigator, tab-navigator, switch-navigator. Please elaborate on your setup.

**Comment by thijs-qv** [comment]
I am using a tab navigator, which contains a stack navigator. I am trying to show the animation when navigating between two screens of the stack navigator.

**Comment by IjzerenHein** [comment]
Alright, that should indeed just work. Can you enable the `debug` prop on the magic-move Scene and Components? This will log out a lot of information that is very useful. Please reply with the log information if you can't figure it out yourselves.
Cheers

**Comment by thijs-qv** [comment]
Thanks for the help, I figured it out. I wrapped the MagicMove.Image and the MagicMove.Text components in a View, which itself was wrapped in a conditional. This was what caused the issue.

**Comment by IjzerenHein** [comment]
Sweet, glad that's resolved :)
